### PR TITLE
CleanEmbeddedChildrenMixin propagate rollback

### PR DESCRIPTION
**Pull request by agebhar1**
Hi,

it solves #3 - what's our opinion?

Best Andreas

### CODE REVIEW

**Comment by lolmaus** [comment]
This is awesome, @agebhar1!

Let me find some time to see your test failing on the current version and passing on the PR version, and i'll merge it.

**Comment by agebhar1** [comment]
thanks ... wait eagerly on your response

**Comment by lolmaus** [comment]
Once again, thank you for your kind effort. I'm greatly excited that my first Ember addon gets a properly tested PR.

Please fix those minor issues:
1. Instead of introducing a new `str` attribute, please reuse the `val` attribute. This PR is feasible without modifying models.
2. Include the name of the tested mixin into test names.

I'm very puzzled on the `start()`/`stop()` stuff:
1. `ember-qunit` says on its [project page](https://github.com/rwjblue/ember-qunit): 
   
   > Under the hood, if you use Ember.RSVP.Promise, ember-qunit will call QUnit's start and stop helpers to stop the test from tearing down and running other tests while your asynchronous code runs. 
   
   If that's so, why does the test fail without manual `start()`/`stop()`?
2. `start()` and `stop()`, but they are [deprecated](http://api.qunitjs.com/QUnit.start/) in QUnit. [`assert.async()`](http://api.qunitjs.com/async/) is recommended to be used instead.
   Unfortunately, to make use of `assert.async()` we have to upgrade test-related dependencies in both Bower and npm, and refactor all tests to use `assert.ok` instead of just `ok`. I wonder whether we should go for it or leave `start()`/`stop()` as they are.
3. Why can't we use `andThen`? I tried it (it takes effort to enable `andThen` in unit tests) and it didn't work. I expected `andThen` to wait for previous promise (`foo.save()`) to finish, but it doesn't. I wonder why?

**Comment by agebhar1** [comment]
Thanks for reviewing this pull request.

I fixed the minor issues 1. and 2. additional both test are more verbose. All tests on PhantomJS failed locally and on TravisCI. But all tests passed on Chrome. 

I also puzzled on the `start()/stop()` stuff and i would investigate some more time . Option (2) sounds good to me and currently the amount of tests are negligible.

How are we going to do next?

**Comment by lolmaus** [comment]
Thank you for your effort.

I will publish this on npm and file a separate issue regarding tests.

**Comment by agebhar1** [comment]
Thanks for merging and i would investigate some more time on the `start()/stop()` stuff.

**Comment by lolmaus** [comment]
I released `v0.4.0`.

I upgraded Ember CLI version in the project which in turn upgraded QUnit. Then i refactored tests to use `assert.ok` instead of global `ok`. This enabled using `assert.async` which i replaced `start`/`stop` with.

A-a-and it repaired Travis builds! It turned out that Phantom didn't support `Function.prototype.bind` until latest versions. This polyfill resolved the issue: https://github.com/pixelhandler/ember-cli-es5-shim

**Comment by agebhar1** [comment]
Awesome

**Pull request merged**
