### PR TITLE
Updated to work with latest ember-data

### LINKED ISSUE #14: isDirty has been deprecated
DEPRECATION: DS.Model#isDirty has been deprecated please use hasDirtyAttributes instead [deprecation id: ds.model.is-dirty-deprecated]

### PR DESCRIPTION
**Pull request by seanrucker**
This will resolve #14 and add support for the latest version of ED.

### CODE REVIEW

**Comment by lolmaus** [comment]
Thank you, I will have a look at it soon.

**Comment by seanrucker** [comment]
How do I run the tests? `npm test` doesn't run anything.

**Comment by lolmaus** [comment]
Either `ember test`, or run `ember s` as you would normally, then access http://localhost:4200/tests/ .

**Comment by seanrucker** [comment]
I started working on updating the tests but ended up going down a rabbit hole...

Requires updating ember-data which requires updating ember-cli which requires removing dependencies on prototype extensions...etc. 

Additionally the payload for the test data needs to change, the template files throw all kinds of deprecation warnings. 

I gave it an hour but unfortunately I need to move on to some other stuff. Might have time to work on this again next week.

**Comment by kmiyashiro** [comment]
I'm interested in getting this done, @seanrucker are you still working on it?

**Comment by lolmaus** [comment]
It's probably easier to restart from scratch. I. e. use an orphan branch.

But I don't have motivation to work on this addon unless there is a known way to mark a parent record as dirty when a relationship is changed.

**Comment by kmiyashiro** [comment]
:crying_cat_face:

**Pull request closed without merging**
